--- #YAML:1.0
name:               License-Syntax
version:            0.13
abstract:           Coding and Decoding of License strings using SPDX and SUSE syntax.
author:
    - Juergen Weigert <jw@suse.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:  1
    Test::More:   0
    Text::CSV:    1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
